# Generated by Django 4.2.1 on 2023-09-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.androidapp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
