# Generated by Django 4.2.1 on 2023-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_completed_at_userprofile_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='app',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app',
            field=models.ManyToManyField(default=6, to='app.androidapp'),
        ),
    ]
