# Generated by Django 4.2.1 on 2023-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_app_userprofile_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app',
            field=models.ManyToManyField(to='app.androidapp'),
        ),
    ]
