# Generated by Django 4.2.1 on 2023-09-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_userprofile_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='android_apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
